[package]
name = "lawn"
version = "0.1.0"
edition = "2024"

[dependencies]
nanorand = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = { git = "https://github.com/bourumir-wyngs/serde-saphyr" }
