[package]
name = "lawn"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = { git = "https://github.com/bourumir-wyngs/serde-saphyr" }
typetag = "0.2.21"

[dev-dependencies]
nanorand = "0.8.0"
divan = "0.1.21"

[[bench]]
name = "main"
harness = false
